# This is a basic workflow to help you get started with Actions

name: CI
on: [push, pull_request]
jobs:
  build:
    name: Test Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install default-jre
      - run: sudo apt install npm
      - run: npm install --global yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test
